// @generated automatically by Diesel CLI.

diesel::table! {
    /// Representation of the `media` table.
    ///
    /// (Automatically generated by Diesel.)
    media (id) {
        /// The `id` column of the `media` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Integer,
        /// The `name` column of the `media` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Text,
        /// The `size` column of the `media` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        size -> Integer,
        /// The `path` column of the `media` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        path -> Text,
        /// The `extension` column of the `media` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        extension -> Text,
        /// The `created_at` column of the `media` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamp,
    }
}
